{
 "title": "AWS Dashboard",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WhichBin invocations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WhichBin invocations",
     "dimensions": { "FunctionName": "WhichBin" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "WhichBin durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "WhichBin durations",
     "dimensions": { "FunctionName": "WhichBin" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "EC2 - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Utilization",
     "dimensions": { "InstanceId": "i-0b93404e70a28da92" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "EC2 - Status check failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Status Check failed",
     "dimensions": { "InstanceId": "i-0b93404e70a28da92" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}