{
 "title": "Hive Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pricePerkWh", "label": "Electricity Price / kWh", "query": "0.1372" },
   { "name": "gaskWhCost", "label": "Gas price / kWh", "query": "0.0306" },
   { "name": "boilerkWhConsumption", "label": "Boiler Consumption / kWh", "query": "28.2" }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption - Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 1000 * $pricePerkWh FROM \"hiveData\" WHERE (\"dataType\" = 'powerConsumption' AND \"dataType\" =~ /^$/) AND $timeFilter GROUP BY time(1m), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 1000 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "powerConsumption" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 1000 * $pricePerkWh FROM \"hiveData\" WHERE (\"dataType\" = 'powerConsumption' AND \"dataType\" =~ /^$/) AND $timeFilter GROUP BY time(1m), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 60 * 4.8 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "Laundry_Cupboard" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_1" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_2" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_spot_3" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hueLightData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 60 * 6.5 * $pricePerkWh FROM \"hueLightData\" WHERE (\"dataType\" = 'lightState' AND \"device\" =~ /Kitchen.+|Bathroom.+/) AND $timeFilter GROUP BY time(1h), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 60 * 4.8 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hueLightData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 60 * 6 * $pricePerkWh FROM \"hueLightData\" WHERE (\"dataType\" = 'lightState' AND \"device\" =~ /Dining.+|Front_room.+/) AND $timeFilter GROUP BY time(1h), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 60 * 4.8 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption - Price",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "format": "currencyGBP",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 1000 * $pricePerkWh FROM \"hiveData\" WHERE (\"dataType\" = 'powerConsumption' OR (\"dataType\" = 'lightState' AND \"device\" = 'Office_1' OR \"device\" = 'Office_2' or \"device\" = 'Office_spot_3' OR \"device\" = 'Laundry_Cupboard')) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 1000 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "powerConsumption" }
     ]
    }
   ]
  },
  {
   "title": "Heating price",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "heatingOn" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / 60 * $boilerkWhConsumption * $gaskWhCost"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "heatingOn" }
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "powerConsumption" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hueLightData",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 60 * 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" }
     ]
    }
   ]
  },
  {
   "title": "Devices on",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hueLightData",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" }
     ]
    }
   ]
  },
  {
   "title": "Lights on",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "query": "SELECT cumulative_sum(last(\"reportedValue\"))  / 1000 * $pricePerkWh FROM \"hiveData\" WHERE (\"dataType\" = 'powerConsumption' AND \"dataType\" =~ /^$/) AND $timeFilter GROUP BY time(1m), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "Laundry_Cupboard" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_1" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_2" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "Office_spot_3" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hueLightData",
     "query": "SELECT last(\"reportedValue\")  FROM \"hueLightData\" WHERE (\"dataType\" = 'lightState' ) AND $timeFilter GROUP BY time(1m), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "reportedValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 60 * 4.8 * $pricePerkWh" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "lightState" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Current temperature",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "currentTemp" }
     ]
    },
    {
     "alias": "Target temperature",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "targetTemp" }
     ]
    }
   ]
  },
  {
   "title": "Heating on",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total minutes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hiveData",
     "select": [
      [
       { "params": [ "heatingOn" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dataType", "operator": "=", "value": "heatingOn" }
     ]
    }
   ]
  }
 ]
}